services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards-provisioning:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    environment:
      - GF_SECURITY_ADMIN_USER=administrator
      - GF_SECURITY_ADMIN_PASSWORD=clearpath
      - GF_USERS_DEFAULT_THEME=light
  air_velocity_subscriber:
      build:
          context: ./
          dockerfile: Dockerfile
      command: ros2 launch subscribe_and_push subscribe_and_push_launch.py
      ports:
        - 8001:8001
volumes:
  prom_data: