global:
  scrape_interval: 1s
  scrape_timeout: 1s
  evaluation_interval: 1s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 1s
    api_version: v1
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 1s
  scrape_timeout: 1s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090
    - 192.168.131.1:8001 # default IP address for the main computer in Clearpath Robotics products
